/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gloomyer_diff_utils_AndroidApkDiffUtils */

#ifndef _Included_com_gloomyer_diff_utils_AndroidApkDiffUtils
#define _Included_com_gloomyer_diff_utils_AndroidApkDiffUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gloomyer_diff_utils_AndroidApkDiffUtils
 * Method:    diff
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT jint JNICALL Java_com_gloomyer_diff_utils_AndroidApkDiffUtils_diff
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
